import pytest

from clients.ghost import Ghost
from clients.mail import Mailgun
from clients.sms import Twilio
from clients.storage import GCS
from config import Settings
from database.sql_db import Database


@pytest.fixture
def sms():
    return Twilio(
        sid=Settings().TWILIO_ACCOUNT_SID,
        token=Settings().TWILIO_AUTH_TOKEN,
        recipient=Settings().TWILIO_RECIPIENT_PHONE,
        sender=Settings().TWILIO_SENDER_PHONE,
    )


@pytest.fixture
def ghost():
    return Ghost(
        admin_api_url=Settings().GHOST_ADMIN_API_URL,
        content_api_url=Settings().GHOST_CONTENT_API_URL,
        client_id=Settings().GHOST_CLIENT_ID,
        client_secret=Settings().GHOST_ADMIN_API_KEY,
        netlify_build_url=Settings().GHOST_NETLIFY_BUILD_HOOK,
    )


@pytest.fixture
def mailgun():
    return Mailgun(
        Settings().MAILGUN_EMAIL_SERVER,
        Settings().MAILGUN_FROM_SENDER,
        Settings().MAILGUN_API_KEY,
    )


@pytest.fixture
def gcs():
    return GCS(
        bucket_name=Settings().GCP_BUCKET_NAME,
        bucket_url=Settings().GCP_BUCKET_URL,
        bucket_lynx=Settings().GCP_LYNX_DIRECTORY,
    )


@pytest.fixture
def rdbms():
    return Database(
        uri=Settings().SQLALCHEMY_DATABASE_URI,
        args=Settings().SQLALCHEMY_ENGINE_OPTIONS,
    )


@pytest.fixture
def github_pr_owner():
    return {
        "action": "opened",
        "number": 198,
        "pull_request": {
            "url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198",
            "id": 532244306,
            "node_id": "MDExOlB1bGxSZXF1ZXN0NTMyMjQ0MzA2",
            "html_url": "https://github.com/toddbirchard/jamstack-api/pull/198",
            "diff_url": "https://github.com/toddbirchard/jamstack-api/pull/198.diff",
            "patch_url": "https://github.com/toddbirchard/jamstack-api/pull/198.patch",
            "issue_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198",
            "number": 198,
            "state": "open",
            "locked": False,
            "title": "Refactor/fastapi",
            "user": {
                "login": "toddbirchard",
                "id": 2747442,
                "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toddbirchard",
                "html_url": "https://github.com/toddbirchard",
                "followers_url": "https://api.github.com/users/toddbirchard/followers",
                "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                "repos_url": "https://api.github.com/users/toddbirchard/repos",
                "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                "type": "User",
                "site_admin": False,
            },
            "body": "yrgrdfhg",
            "created_at": "2020-12-04T02:39:51Z",
            "updated_at": "2020-12-04T02:39:51Z",
            "assignees": [],
            "requested_reviewers": [],
            "requested_teams": [],
            "labels": [
                {
                    "id": 1891195455,
                    "node_id": "MDU6TGFiZWwxODkxMTk1NDU1",
                    "url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels/enhancement",
                    "name": "enhancement",
                    "color": "a2eeef",
                    "default": True,
                    "description": "New feature or request",
                }
            ],
            "draft": False,
            "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/commits",
            "review_comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/comments",
            "review_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/comments{/number}",
            "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198/comments",
            "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/ac32cb13139b8db93459317d8dff2eb0b827afc6",
            "head": {
                "label": "toddbirchard:refactor/fastapi",
                "ref": "refactor/fastapi",
                "sha": "ac32cb13139b8db93459317d8dff2eb0b827afc6",
                "user": {
                    "login": "toddbirchard",
                    "id": 2747442,
                    "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/toddbirchard",
                    "html_url": "https://github.com/toddbirchard",
                    "followers_url": "https://api.github.com/users/toddbirchard/followers",
                    "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                    "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                    "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                    "repos_url": "https://api.github.com/users/toddbirchard/repos",
                    "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "repo": {
                    "id": 245327108,
                    "node_id": "MDEwOlJlcG9zaXRvcnkyNDUzMjcxMDg=",
                    "name": "jamstack-api",
                    "full_name": "toddbirchard/jamstack-api",
                    "private": False,
                    "owner": {
                        "login": "toddbirchard",
                        "id": 2747442,
                        "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/toddbirchard",
                        "html_url": "https://github.com/toddbirchard",
                        "followers_url": "https://api.github.com/users/toddbirchard/followers",
                        "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                        "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                        "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                        "repos_url": "https://api.github.com/users/toddbirchard/repos",
                        "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                        "type": "User",
                        "site_admin": False,
                    },
                    "html_url": "https://github.com/toddbirchard/jamstack-api",
                    "description": ":guitar: :books: API to automate optimizations for JAMStack sites.",
                    "fork": False,
                    "url": "https://api.github.com/repos/toddbirchard/jamstack-api",
                    "forks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/forks",
                    "keys_url": "https://api.github.com/repos/toddbirchard/jamstack-api/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/toddbirchard/jamstack-api/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/toddbirchard/jamstack-api/teams",
                    "hooks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/hooks",
                    "issue_events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/events",
                    "assignees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/toddbirchard/jamstack-api/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/tags",
                    "blobs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/toddbirchard/jamstack-api/languages",
                    "stargazers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/stargazers",
                    "contributors_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contributors",
                    "subscribers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscribers",
                    "subscription_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscription",
                    "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/toddbirchard/jamstack-api/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/toddbirchard/jamstack-api/merges",
                    "archive_url": "https://api.github.com/repos/toddbirchard/jamstack-api/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/toddbirchard/jamstack-api/downloads",
                    "issues_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/toddbirchard/jamstack-api/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/toddbirchard/jamstack-api/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels{/name}",
                    "releases_url": "https://api.github.com/repos/toddbirchard/jamstack-api/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/deployments",
                    "created_at": "2020-03-06T04:07:25Z",
                    "updated_at": "2020-12-01T20:46:52Z",
                    "pushed_at": "2020-12-04T02:39:32Z",
                    "git_url": "git://github.com/toddbirchard/jamstack-api.git",
                    "ssh_url": "git@github.com:toddbirchard/jamstack-api.git",
                    "clone_url": "https://github.com/toddbirchard/jamstack-api.git",
                    "svn_url": "https://github.com/toddbirchard/jamstack-api",
                    "homepage": "",
                    "size": 1206,
                    "stargazers_count": 3,
                    "watchers_count": 3,
                    "language": "HTML",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 6,
                    "forks": 0,
                    "open_issues": 6,
                    "watchers": 3,
                    "default_branch": "master",
                    "allow_squash_merge": True,
                    "allow_merge_commit": True,
                    "allow_rebase_merge": True,
                    "delete_branch_on_merge": False,
                },
            },
            "base": {
                "label": "toddbirchard:master",
                "ref": "master",
                "sha": "1196b3c1f0fc449f70c088cc8f35bdfa01b69b04",
                "user": {
                    "login": "toddbirchard",
                    "id": 2747442,
                    "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/toddbirchard",
                    "html_url": "https://github.com/toddbirchard",
                    "followers_url": "https://api.github.com/users/toddbirchard/followers",
                    "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                    "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                    "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                    "repos_url": "https://api.github.com/users/toddbirchard/repos",
                    "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "repo": {
                    "id": 245327108,
                    "node_id": "MDEwOlJlcG9zaXRvcnkyNDUzMjcxMDg=",
                    "name": "jamstack-api",
                    "full_name": "toddbirchard/jamstack-api",
                    "private": False,
                    "owner": {
                        "login": "toddbirchard",
                        "id": 2747442,
                        "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/toddbirchard",
                        "html_url": "https://github.com/toddbirchard",
                        "followers_url": "https://api.github.com/users/toddbirchard/followers",
                        "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                        "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                        "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                        "repos_url": "https://api.github.com/users/toddbirchard/repos",
                        "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                        "type": "User",
                        "site_admin": False,
                    },
                    "html_url": "https://github.com/toddbirchard/jamstack-api",
                    "description": ":guitar: :books: API to automate optimizations for JAMStack sites.",
                    "fork": False,
                    "url": "https://api.github.com/repos/toddbirchard/jamstack-api",
                    "forks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/forks",
                    "keys_url": "https://api.github.com/repos/toddbirchard/jamstack-api/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/toddbirchard/jamstack-api/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/toddbirchard/jamstack-api/teams",
                    "hooks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/hooks",
                    "issue_events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/events",
                    "assignees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/toddbirchard/jamstack-api/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/tags",
                    "blobs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/toddbirchard/jamstack-api/languages",
                    "stargazers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/stargazers",
                    "contributors_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contributors",
                    "subscribers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscribers",
                    "subscription_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscription",
                    "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/toddbirchard/jamstack-api/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/toddbirchard/jamstack-api/merges",
                    "archive_url": "https://api.github.com/repos/toddbirchard/jamstack-api/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/toddbirchard/jamstack-api/downloads",
                    "issues_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/toddbirchard/jamstack-api/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/toddbirchard/jamstack-api/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels{/name}",
                    "releases_url": "https://api.github.com/repos/toddbirchard/jamstack-api/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/deployments",
                    "created_at": "2020-03-06T04:07:25Z",
                    "updated_at": "2020-12-01T20:46:52Z",
                    "pushed_at": "2020-12-04T02:39:32Z",
                    "git_url": "git://github.com/toddbirchard/jamstack-api.git",
                    "ssh_url": "git@github.com:toddbirchard/jamstack-api.git",
                    "clone_url": "https://github.com/toddbirchard/jamstack-api.git",
                    "svn_url": "https://github.com/toddbirchard/jamstack-api",
                    "homepage": "",
                    "size": 1206,
                    "stargazers_count": 3,
                    "watchers_count": 3,
                    "language": "HTML",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 6,
                    "forks": 0,
                    "open_issues": 6,
                    "watchers": 3,
                    "default_branch": "master",
                    "allow_squash_merge": True,
                    "allow_merge_commit": True,
                    "allow_rebase_merge": True,
                    "delete_branch_on_merge": False,
                },
            },
            "_links": {
                "self": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198"
                },
                "html": {
                    "href": "https://github.com/toddbirchard/jamstack-api/pull/198"
                },
                "issue": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198"
                },
                "comments": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198/comments"
                },
                "review_comments": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/comments"
                },
                "review_comment": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/comments{/number}"
                },
                "commits": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/commits"
                },
                "statuses": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/ac32cb13139b8db93459317d8dff2eb0b827afc6"
                },
            },
            "author_association": "OWNER",
            "merged": False,
            "mergeable_state": "unknown",
            "comments": 0,
            "review_comments": 0,
            "maintainer_can_modify": False,
            "commits": 4,
            "additions": 1650,
            "deletions": 1016,
            "changed_files": 91,
        },
        "repository": {
            "id": 245327108,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNDUzMjcxMDg=",
            "name": "jamstack-api",
            "full_name": "toddbirchard/jamstack-api",
            "private": False,
            "owner": {
                "login": "toddbirchard",
                "id": 2747442,
                "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toddbirchard",
                "html_url": "https://github.com/toddbirchard",
                "followers_url": "https://api.github.com/users/toddbirchard/followers",
                "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                "repos_url": "https://api.github.com/users/toddbirchard/repos",
                "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                "type": "User",
                "site_admin": False,
            },
            "html_url": "https://github.com/toddbirchard/jamstack-api",
            "description": ":guitar: :books: API to automate optimizations for JAMStack sites.",
            "fork": False,
            "url": "https://api.github.com/repos/toddbirchard/jamstack-api",
            "forks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/forks",
            "keys_url": "https://api.github.com/repos/toddbirchard/jamstack-api/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/toddbirchard/jamstack-api/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/toddbirchard/jamstack-api/teams",
            "hooks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/hooks",
            "issue_events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/events{/number}",
            "events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/events",
            "assignees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/assignees{/user}",
            "branches_url": "https://api.github.com/repos/toddbirchard/jamstack-api/branches{/branch}",
            "tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/tags",
            "blobs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/toddbirchard/jamstack-api/languages",
            "stargazers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/stargazers",
            "contributors_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contributors",
            "subscribers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscribers",
            "subscription_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscription",
            "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contents/{+path}",
            "compare_url": "https://api.github.com/repos/toddbirchard/jamstack-api/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/toddbirchard/jamstack-api/merges",
            "archive_url": "https://api.github.com/repos/toddbirchard/jamstack-api/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/toddbirchard/jamstack-api/downloads",
            "issues_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues{/number}",
            "pulls_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/toddbirchard/jamstack-api/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/toddbirchard/jamstack-api/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels{/name}",
            "releases_url": "https://api.github.com/repos/toddbirchard/jamstack-api/releases{/id}",
            "deployments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/deployments",
            "created_at": "2020-03-06T04:07:25Z",
            "updated_at": "2020-12-01T20:46:52Z",
            "pushed_at": "2020-12-04T02:39:32Z",
            "git_url": "git://github.com/toddbirchard/jamstack-api.git",
            "ssh_url": "git@github.com:toddbirchard/jamstack-api.git",
            "clone_url": "https://github.com/toddbirchard/jamstack-api.git",
            "svn_url": "https://github.com/toddbirchard/jamstack-api",
            "homepage": "",
            "size": 1206,
            "stargazers_count": 3,
            "watchers_count": 3,
            "language": "HTML",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 0,
            "archived": False,
            "disabled": False,
            "open_issues_count": 6,
            "forks": 0,
            "open_issues": 6,
            "watchers": 3,
            "default_branch": "master",
        },
        "sender": {
            "login": "toddbirchard",
            "id": 2747442,
            "node_id": "MDQ6VXNlcjI3NDc0NDI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/toddbirchard",
            "html_url": "https://github.com/toddbirchard",
            "followers_url": "https://api.github.com/users/toddbirchard/followers",
            "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
            "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
            "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
            "repos_url": "https://api.github.com/users/toddbirchard/repos",
            "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
            "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
            "type": "User",
            "site_admin": False,
        },
    }


@pytest.fixture
def github_pr_user():
    return {
        "action": "opened",
        "number": 198,
        "pull_request": {
            "url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198",
            "id": 532244306,
            "node_id": "MDExOlB1bGxSZXF1ZXN0NTMyMjQ0MzA2",
            "html_url": "https://github.com/toddbirchard/jamstack-api/pull/198",
            "diff_url": "https://github.com/toddbirchard/jamstack-api/pull/198.diff",
            "patch_url": "https://github.com/toddbirchard/jamstack-api/pull/198.patch",
            "issue_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198",
            "number": 198,
            "state": "open",
            "locked": False,
            "title": "Refactor/fastapi",
            "user": {
                "login": "toddbirchard",
                "id": 2747442,
                "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toddbirchard",
                "html_url": "https://github.com/toddbirchard",
                "followers_url": "https://api.github.com/users/toddbirchard/followers",
                "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                "repos_url": "https://api.github.com/users/toddbirchard/repos",
                "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                "type": "User",
                "site_admin": False,
            },
            "body": "yrgrdfhg",
            "created_at": "2020-12-04T02:39:51Z",
            "updated_at": "2020-12-04T02:39:51Z",
            "assignees": [],
            "requested_reviewers": [],
            "requested_teams": [],
            "labels": [
                {
                    "id": 1891195455,
                    "node_id": "MDU6TGFiZWwxODkxMTk1NDU1",
                    "url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels/enhancement",
                    "name": "enhancement",
                    "color": "a2eeef",
                    "default": True,
                    "description": "New feature or request",
                }
            ],
            "draft": False,
            "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/commits",
            "review_comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/comments",
            "review_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/comments{/number}",
            "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198/comments",
            "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/ac32cb13139b8db93459317d8dff2eb0b827afc6",
            "head": {
                "label": "toddbirchard:refactor/fastapi",
                "ref": "refactor/fastapi",
                "sha": "ac32cb13139b8db93459317d8dff2eb0b827afc6",
                "user": {
                    "login": "toddbirchard",
                    "id": 2747442,
                    "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/toddbirchard",
                    "html_url": "https://github.com/toddbirchard",
                    "followers_url": "https://api.github.com/users/toddbirchard/followers",
                    "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                    "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                    "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                    "repos_url": "https://api.github.com/users/toddbirchard/repos",
                    "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "repo": {
                    "id": 245327108,
                    "node_id": "MDEwOlJlcG9zaXRvcnkyNDUzMjcxMDg=",
                    "name": "jamstack-api",
                    "full_name": "toddbirchard/jamstack-api",
                    "private": False,
                    "owner": {
                        "login": "toddbirchard",
                        "id": 2747442,
                        "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/toddbirchard",
                        "html_url": "https://github.com/toddbirchard",
                        "followers_url": "https://api.github.com/users/toddbirchard/followers",
                        "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                        "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                        "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                        "repos_url": "https://api.github.com/users/toddbirchard/repos",
                        "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                        "type": "User",
                        "site_admin": False,
                    },
                    "html_url": "https://github.com/toddbirchard/jamstack-api",
                    "description": ":guitar: :books: API to automate optimizations for JAMStack sites.",
                    "fork": False,
                    "url": "https://api.github.com/repos/toddbirchard/jamstack-api",
                    "forks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/forks",
                    "keys_url": "https://api.github.com/repos/toddbirchard/jamstack-api/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/toddbirchard/jamstack-api/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/toddbirchard/jamstack-api/teams",
                    "hooks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/hooks",
                    "issue_events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/events",
                    "assignees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/toddbirchard/jamstack-api/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/tags",
                    "blobs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/toddbirchard/jamstack-api/languages",
                    "stargazers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/stargazers",
                    "contributors_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contributors",
                    "subscribers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscribers",
                    "subscription_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscription",
                    "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/toddbirchard/jamstack-api/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/toddbirchard/jamstack-api/merges",
                    "archive_url": "https://api.github.com/repos/toddbirchard/jamstack-api/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/toddbirchard/jamstack-api/downloads",
                    "issues_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/toddbirchard/jamstack-api/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/toddbirchard/jamstack-api/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels{/name}",
                    "releases_url": "https://api.github.com/repos/toddbirchard/jamstack-api/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/deployments",
                    "created_at": "2020-03-06T04:07:25Z",
                    "updated_at": "2020-12-01T20:46:52Z",
                    "pushed_at": "2020-12-04T02:39:32Z",
                    "git_url": "git://github.com/toddbirchard/jamstack-api.git",
                    "ssh_url": "git@github.com:toddbirchard/jamstack-api.git",
                    "clone_url": "https://github.com/toddbirchard/jamstack-api.git",
                    "svn_url": "https://github.com/toddbirchard/jamstack-api",
                    "homepage": "",
                    "size": 1206,
                    "stargazers_count": 3,
                    "watchers_count": 3,
                    "language": "HTML",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 6,
                    "forks": 0,
                    "open_issues": 6,
                    "watchers": 3,
                    "default_branch": "master",
                    "allow_squash_merge": True,
                    "allow_merge_commit": True,
                    "allow_rebase_merge": True,
                    "delete_branch_on_merge": False,
                },
            },
            "base": {
                "label": "toddbirchard:master",
                "ref": "master",
                "sha": "1196b3c1f0fc449f70c088cc8f35bdfa01b69b04",
                "user": {
                    "login": "fakeuser",
                    "id": 2747442,
                    "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/toddbirchard",
                    "html_url": "https://github.com/toddbirchard",
                    "followers_url": "https://api.github.com/users/toddbirchard/followers",
                    "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                    "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                    "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                    "repos_url": "https://api.github.com/users/toddbirchard/repos",
                    "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "repo": {
                    "id": 245327108,
                    "node_id": "MDEwOlJlcG9zaXRvcnkyNDUzMjcxMDg=",
                    "name": "jamstack-api",
                    "full_name": "toddbirchard/jamstack-api",
                    "private": False,
                    "owner": {
                        "login": "fakeuser",
                        "id": 2747442,
                        "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/toddbirchard",
                        "html_url": "https://github.com/toddbirchard",
                        "followers_url": "https://api.github.com/users/toddbirchard/followers",
                        "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                        "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                        "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                        "repos_url": "https://api.github.com/users/toddbirchard/repos",
                        "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                        "type": "User",
                        "site_admin": False,
                    },
                    "html_url": "https://github.com/toddbirchard/jamstack-api",
                    "description": ":guitar: :books: API to automate optimizations for JAMStack sites.",
                    "fork": False,
                    "url": "https://api.github.com/repos/toddbirchard/jamstack-api",
                    "forks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/forks",
                    "keys_url": "https://api.github.com/repos/toddbirchard/jamstack-api/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/toddbirchard/jamstack-api/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/toddbirchard/jamstack-api/teams",
                    "hooks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/hooks",
                    "issue_events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/events",
                    "assignees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/toddbirchard/jamstack-api/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/tags",
                    "blobs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/toddbirchard/jamstack-api/languages",
                    "stargazers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/stargazers",
                    "contributors_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contributors",
                    "subscribers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscribers",
                    "subscription_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscription",
                    "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/toddbirchard/jamstack-api/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/toddbirchard/jamstack-api/merges",
                    "archive_url": "https://api.github.com/repos/toddbirchard/jamstack-api/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/toddbirchard/jamstack-api/downloads",
                    "issues_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/toddbirchard/jamstack-api/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/toddbirchard/jamstack-api/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels{/name}",
                    "releases_url": "https://api.github.com/repos/toddbirchard/jamstack-api/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/deployments",
                    "created_at": "2020-03-06T04:07:25Z",
                    "updated_at": "2020-12-01T20:46:52Z",
                    "pushed_at": "2020-12-04T02:39:32Z",
                    "git_url": "git://github.com/toddbirchard/jamstack-api.git",
                    "ssh_url": "git@github.com:toddbirchard/jamstack-api.git",
                    "clone_url": "https://github.com/toddbirchard/jamstack-api.git",
                    "svn_url": "https://github.com/toddbirchard/jamstack-api",
                    "homepage": "",
                    "size": 1206,
                    "stargazers_count": 3,
                    "watchers_count": 3,
                    "language": "HTML",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 6,
                    "forks": 0,
                    "open_issues": 6,
                    "watchers": 3,
                    "default_branch": "master",
                    "allow_squash_merge": True,
                    "allow_merge_commit": True,
                    "allow_rebase_merge": True,
                    "delete_branch_on_merge": False,
                },
            },
            "_links": {
                "self": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198"
                },
                "html": {
                    "href": "https://github.com/toddbirchard/jamstack-api/pull/198"
                },
                "issue": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198"
                },
                "comments": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/198/comments"
                },
                "review_comments": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/comments"
                },
                "review_comment": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/comments{/number}"
                },
                "commits": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls/198/commits"
                },
                "statuses": {
                    "href": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/ac32cb13139b8db93459317d8dff2eb0b827afc6"
                },
            },
            "author_association": "OWNER",
            "merged": False,
            "mergeable_state": "unknown",
            "comments": 0,
            "review_comments": 0,
            "maintainer_can_modify": False,
            "commits": 4,
            "additions": 1650,
            "deletions": 1016,
            "changed_files": 91,
        },
        "repository": {
            "id": 245327108,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNDUzMjcxMDg=",
            "name": "jamstack-api",
            "full_name": "toddbirchard/jamstack-api",
            "private": False,
            "owner": {
                "login": "toddbirchard",
                "id": 2747442,
                "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toddbirchard",
                "html_url": "https://github.com/toddbirchard",
                "followers_url": "https://api.github.com/users/toddbirchard/followers",
                "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                "repos_url": "https://api.github.com/users/toddbirchard/repos",
                "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                "type": "User",
                "site_admin": False,
            },
            "html_url": "https://github.com/toddbirchard/jamstack-api",
            "description": ":guitar: :books: API to automate optimizations for JAMStack sites.",
            "fork": False,
            "url": "https://api.github.com/repos/toddbirchard/jamstack-api",
            "forks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/forks",
            "keys_url": "https://api.github.com/repos/toddbirchard/jamstack-api/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/toddbirchard/jamstack-api/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/toddbirchard/jamstack-api/teams",
            "hooks_url": "https://api.github.com/repos/toddbirchard/jamstack-api/hooks",
            "issue_events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/events{/number}",
            "events_url": "https://api.github.com/repos/toddbirchard/jamstack-api/events",
            "assignees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/assignees{/user}",
            "branches_url": "https://api.github.com/repos/toddbirchard/jamstack-api/branches{/branch}",
            "tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/tags",
            "blobs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/toddbirchard/jamstack-api/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/toddbirchard/jamstack-api/languages",
            "stargazers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/stargazers",
            "contributors_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contributors",
            "subscribers_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscribers",
            "subscription_url": "https://api.github.com/repos/toddbirchard/jamstack-api/subscription",
            "commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/toddbirchard/jamstack-api/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/toddbirchard/jamstack-api/contents/{+path}",
            "compare_url": "https://api.github.com/repos/toddbirchard/jamstack-api/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/toddbirchard/jamstack-api/merges",
            "archive_url": "https://api.github.com/repos/toddbirchard/jamstack-api/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/toddbirchard/jamstack-api/downloads",
            "issues_url": "https://api.github.com/repos/toddbirchard/jamstack-api/issues{/number}",
            "pulls_url": "https://api.github.com/repos/toddbirchard/jamstack-api/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/toddbirchard/jamstack-api/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/toddbirchard/jamstack-api/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/toddbirchard/jamstack-api/labels{/name}",
            "releases_url": "https://api.github.com/repos/toddbirchard/jamstack-api/releases{/id}",
            "deployments_url": "https://api.github.com/repos/toddbirchard/jamstack-api/deployments",
            "created_at": "2020-03-06T04:07:25Z",
            "updated_at": "2020-12-01T20:46:52Z",
            "pushed_at": "2020-12-04T02:39:32Z",
            "git_url": "git://github.com/toddbirchard/jamstack-api.git",
            "ssh_url": "git@github.com:toddbirchard/jamstack-api.git",
            "clone_url": "https://github.com/toddbirchard/jamstack-api.git",
            "svn_url": "https://github.com/toddbirchard/jamstack-api",
            "homepage": "",
            "size": 1206,
            "stargazers_count": 3,
            "watchers_count": 3,
            "language": "HTML",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 0,
            "archived": False,
            "disabled": False,
            "open_issues_count": 6,
            "forks": 0,
            "open_issues": 6,
            "watchers": 3,
            "default_branch": "master",
        },
        "sender": {
            "login": "fakeuser",
            "id": 2747442,
            "node_id": "MDQ6VXNlcjI3NDc0NDI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/toddbirchard",
            "html_url": "https://github.com/toddbirchard",
            "followers_url": "https://api.github.com/users/toddbirchard/followers",
            "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
            "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
            "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
            "repos_url": "https://api.github.com/users/toddbirchard/repos",
            "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
            "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
            "type": "User",
            "site_admin": False,
        },
    }


@pytest.fixture
def github_issue_user():
    return {
        "action": "opened",
        "issue": {
            "url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues/21",
            "repository_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial",
            "labels_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues/21/labels{/name}",
            "comments_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues/21/comments",
            "events_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues/21/events",
            "html_url": "https://github.com/toddbirchard/flasklogin-tutorial/issues/21",
            "id": 756606573,
            "node_id": "MDU6SXNzdWU3NTY2MDY1NzM=",
            "number": 21,
            "title": "Test issue",
            "user": {
                "login": "fakeuser",
                "id": 2747442,
                "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toddbirchard",
                "html_url": "https://github.com/toddbirchard",
                "followers_url": "https://api.github.com/users/toddbirchard/followers",
                "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                "repos_url": "https://api.github.com/users/toddbirchard/repos",
                "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                "type": "User",
                "site_admin": False,
            },
            "labels": [
                {
                    "id": 1304794335,
                    "node_id": "MDU6TGFiZWwxMzA0Nzk0MzM1",
                    "url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/labels/question",
                    "name": "question",
                    "color": "d876e3",
                    "default": True,
                    "description": "Further information is requested",
                }
            ],
            "state": "open",
            "locked": False,
            "assignees": [],
            "comments": 0,
            "created_at": "2020-12-03T21:32:15Z",
            "updated_at": "2020-12-03T21:32:15Z",
            "author_association": "OWNER",
            "body": "Creating this to test our automation tool.",
        },
        "repository": {
            "id": 179583023,
            "node_id": "MDEwOlJlcG9zaXRvcnkxNzk1ODMwMjM=",
            "name": "flasklogin-tutorial",
            "full_name": "toddbirchard/flasklogin-tutorial",
            "private": False,
            "owner": {
                "login": "toddbirchard",
                "id": 2747442,
                "node_id": "MDQ6VXNlcjI3NDc0NDI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toddbirchard",
                "html_url": "https://github.com/toddbirchard",
                "followers_url": "https://api.github.com/users/toddbirchard/followers",
                "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
                "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
                "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
                "repos_url": "https://api.github.com/users/toddbirchard/repos",
                "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
                "type": "User",
                "site_admin": False,
            },
            "html_url": "https://github.com/toddbirchard/flasklogin-tutorial",
            "description": ":man_technologist: :key: Tutorial to accompany corresponding post on hackersandslackers.com",
            "fork": False,
            "url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial",
            "forks_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/forks",
            "keys_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/teams",
            "hooks_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/hooks",
            "issue_events_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues/events{/number}",
            "events_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/events",
            "assignees_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/assignees{/user}",
            "branches_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/branches{/branch}",
            "tags_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/tags",
            "blobs_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/languages",
            "stargazers_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/stargazers",
            "contributors_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/contributors",
            "subscribers_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/subscribers",
            "subscription_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/subscription",
            "commits_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/contents/{+path}",
            "compare_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/merges",
            "archive_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/downloads",
            "issues_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/issues{/number}",
            "pulls_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/labels{/name}",
            "releases_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/releases{/id}",
            "deployments_url": "https://api.github.com/repos/toddbirchard/flasklogin-tutorial/deployments",
            "created_at": "2019-04-04T21:56:12Z",
            "updated_at": "2020-11-30T02:57:21Z",
            "pushed_at": "2020-11-30T02:57:19Z",
            "git_url": "git://github.com/toddbirchard/flasklogin-tutorial.git",
            "ssh_url": "git@github.com:toddbirchard/flasklogin-tutorial.git",
            "clone_url": "https://github.com/toddbirchard/flasklogin-tutorial.git",
            "svn_url": "https://github.com/toddbirchard/flasklogin-tutorial",
            "homepage": "https://hackersandslackers.com/authenticating-users-with-flask-login/",
            "size": 235,
            "stargazers_count": 95,
            "watchers_count": 95,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 39,
            "archived": False,
            "disabled": False,
            "open_issues_count": 10,
            "forks": 39,
            "open_issues": 10,
            "watchers": 95,
            "default_branch": "master",
        },
        "sender": {
            "login": "fakeuser",
            "id": 2747442,
            "node_id": "MDQ6VXNlcjI3NDc0NDI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2747442?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/toddbirchard",
            "html_url": "https://github.com/toddbirchard",
            "followers_url": "https://api.github.com/users/toddbirchard/followers",
            "following_url": "https://api.github.com/users/toddbirchard/following{/other_user}",
            "gists_url": "https://api.github.com/users/toddbirchard/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/toddbirchard/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/toddbirchard/subscriptions",
            "organizations_url": "https://api.github.com/users/toddbirchard/orgs",
            "repos_url": "https://api.github.com/users/toddbirchard/repos",
            "events_url": "https://api.github.com/users/toddbirchard/events{/privacy}",
            "received_events_url": "https://api.github.com/users/toddbirchard/received_events",
            "type": "User",
            "site_admin": False,
        },
    }
